# Generated by Django 5.1.5 on 2025-01-24 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_department_rename_is_reviewer_user_is_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='job_title',
        ),
    ]
