# Generated by Django 5.1.5 on 2025-01-24 13:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incoming',
            name='conf',
            field=models.BooleanField(default=False, verbose_name='is confidential'),
        ),
        migrations.AlterField(
            model_name='incoming',
            name='received',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='incoming',
            name='urgent',
            field=models.BooleanField(default=False, verbose_name='is urgent'),
        ),
    ]
