# Generated by Django 5.1.5 on 2025-01-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_incoming_conf_alter_incoming_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incoming',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
